Seminar2 과제 구현
AND-SOPT-SERVER/hyerin.hwang pull request #4
Opened 2024-10-18 15:12 UTC by hyerinhwang-sailin

# 기획 요구사항
- 일기 작성
     - 30자 제한
     - 중복 제목 방지
     - 5분에 하나씩 작성(마지막 일기 작성 시간 기준)
- 내 일기 목록 조회
    - 10개 보여주기
    - 카테고리 별 조회
    - 정렬 기준 : 최신 등록 순 / 글자 수 많은 순
- 일기 상세 조회
- 일기 수정
    - 30자 제한
    - 중복 제목 방지
- 일기 제거

# 구현 방법
## 일기 30자 제한
request body를 검증하는 것이기에 controller 레이어에서 length를 검증해 30자 초과 시 400 에러를 반환하도록 했습니다.

## 중복 제목 방지
기존 제목들을 db에서 조회하기에 service에서 검증해 중복된 제목일 시 409 에러를 반환하도록 했습니다.
수정으로 인해 중복된 제목이 발생하는 것은 기획의도에 어긋난다고 생각해서 수정 시에도 제목을 바꿨을 경우 기존 제목과 중복되면 에러를 반환하도록 구현했습니다.

## 5분에 하나씩 일기 작성
스프링 처리율 제한을 구현하는 라이브러리 중 토큰 버킷 알고리즘을 기반으로 한 Java 속도 제한 라이브러리인 Bucket4J를 이용해 구현했습니다.
처리율 제한을 구현할 수 있는 방법이 여러가지 있는데 제일 안정적이고 확장하기에도 용이하다고 하여 선택했습니다. 아래 링크를 참고해주세요!
https://hogwart-scholars.tistory.com/entry/Spring-Boot-%EC%9E%90%EB%B0%94-%EC%8A%A4%ED%94%84%EB%A7%81%EC%97%90%EC%84%9C-%EC%B2%98%EB%A6%AC%EC%9C%A8-%EC%A0%9C%ED%95%9C-%EA%B8%B0%EB%8A%A5%EC%9D%84-%EA%B5%AC%ED%98%84%ED%95%98%EB%8A%94-4%EA%B0%80%EC%A7%80-%EB%B0%A9%EB%B2%95

간단히 설명하자면 기본적으로 토큰이 1개 존재하고 일기 생성 시 1개를 소모하고, 5분 뒤 토큰이 충전되는 형태입니다. db 조회 없이 메모리에 저장된 토큰으로 판단하고, 5분이라는 시간 제한은 바뀔 수 있는 비즈니스 로직이라고 생각해 service 패키지에 작성했고, 성능 측면에서도 장점이 있다고 합니다.
토큰이 존재하면 일기를 생성할 수 있고, 존재하지 않으면, 즉 5분 내에 일기를 작성할 경우 429 TooManyRequest 에러를 반환하도록 했습니다.

## 일기 10개씩 보여주기
Spring Pageable을 이용해 보여주도록 구현했습니다.

## 카테고리별 일기 목록 조회
카테고리는 enum으로 다양한 카테고리를 받을 수 있도록 작성했고 DiaryEntity에 함께 저장하기 위해 repository 패키지에 넣었습니다.
일기 목록 조회 시 param으로 받은 후 DiaryRepository에 조회 로직을 통해  필터링하도록 구현했습니다.

## 정렬기준별 일기 목록 조회
정렬기준(OrderBy) enum을 생성한 후 일기 목록 조회 시 param으로 받아서 조회 및 정렬하도록 구현했습니다. 클라이언트와의 소통 용도로만 쓰기에 dto 패키지에 넣었습니다.
최신 등록 순, 글자 수 많은 순으로 조회할 수 있도록 쿼리문을 작성해 DiaryRepository에 조회 로직을 작성했습니다. 만약 동일한 글자 수의 일기가 존재해 조회된 일기 수가 10개 초과인 경우 최신 등록 순으로 두 번째 기준을 마련했습니다. 카테고리별로 조회하면서 글자 수 많은 순으로 조회하는 경우에도 동일한 2차 기준을 마련해 조회하도록 했습니다.

## Success, Error 커스텀
exception을 가독성 좋게 확인할 수 있도록 SuccessCode와 ErrorCode를 커스텀했습니다. 코드로 확인해주세요.

# To Reviewers
1. postman으로 테스트 다 해봤는데 시험기간 이슈로 캡처까지해서 정리하기엔 너무 힘들어서..ㅎㅎ 언젠가 올릴게요.. 의도한대로 구현된 건 확인했습니다!
2. 에러 커스텀 방식에 대해서 피드백 듣고 싶어요!
3. 검증 로직을 어디 레이어의 책임으로 둘지 고민하면서 코드 작성했는데 같이 이야기 나누고 싶습니다!
4. 모든 의견 환영합니다~~

2024-10-29 11:44 UTC, daehwan2da requested changes

2024-10-29 11:44 UTC, daehwan2da commented on src/main/java/org/sopt/diary/api/DiaryController.java
> +		if (diaryCreateRequest.body().length() > 30) {
body 가 null 로 request 가 들어오면 500 에러가 날 것같아요

``` json
{
  "title" : "abc"
}
```
이렇게 요청들어오면 DirayCreateRequest 가 파싱될때 body 가 null 로 채워질거고, body().length() 이부분에서 NPE 가날것으로 보이네요

2024-10-29 11:44 UTC, daehwan2da commented on src/main/java/org/sopt/diary/api/dto/DiaryCreateRequest.java
> +	Category category
Category enum 에서 정의되지 않은 문자가 request 로 들어오면 어떻게 될까요?

``` json
{
  "title" : "abc",
  "body" : "abc",
  "category" : "abc"
}
```

2024-10-29 11:44 UTC, daehwan2da commented on src/main/java/org/sopt/diary/service/DiaryRateLimiter.java
> +		this.bucket = Bucket.builder().addLimit(limit).build();
의도한 방향은 아닌데요, Bucket4j 사용하는 방향도 좋은것같습니다~
다만 아래 내용을 추가로 확인해보면 좋을것같아요.
- 5분이라는 시간을 스케줄링하는 처리가 필요할텐데, 어떤 쓰레드를 어떻게 할당해서 처리하는지? 
- 동시에 요청이 들어오는 경우에도 thread safe 하게 처리되는지?

2024-10-29 11:44 UTC, daehwan2da commented on src/main/java/org/sopt/diary/service/DiaryService.java
> +		boolean existsByTitle = diaryRepository.existsByTitle(diaryCreateRequest.title());
중복체크를 서비스 레이어에서 하게되면 어떤 문제가 있을수있을까요?
- 동시에 같은 요청이 들어온 경우를 고민해보면 좋을것같아요
  - 아직 디비에 저장되지 않은 title : a 의 요청이 동시에 들어와서 둘 다 exist 는 false 가 나온 케이스

2024-10-29 11:44 UTC, daehwan2da commented on src/main/java/org/sopt/diary/api/DiaryController.java
> +		@RequestParam(required = false) Category category,
parameter 가 Category enum 에 정의되지 않은 값으로 입력되면 어떻게될까요?

2024-10-29 11:44 UTC, daehwan2da commented on src/main/java/org/sopt/diary/api/DiaryController.java
> +		@RequestParam(defaultValue = "CREATED_AT") OrderBy orderBy
OrderBy 도 마찬가지에요

2024-10-29 11:44 UTC, daehwan2da commented on src/main/java/org/sopt/diary/service/DiaryService.java
> +	public Diary getDiaryDetail(DiaryDetailRequest diaryDetailRequest) {
Service 에서 RequestDto 를 알지 않는게 좋을것같아요 (역의존이 생김 Service -> Controller)
풀어서 메서드 파라미터를 구성해보는건 어떨까요

2024-10-29 11:44 UTC, daehwan2da commented on src/main/java/org/sopt/diary/service/DiaryService.java
> +			.orElseThrow(() -> new NotFoundException(DiaryErrorCode.DIARY_NOT_FOUND));
이미 예외에서 NotFound 인데 ErrorCode 에서 똑같이 NotFound 를 명시할 필요가 있을까요?

2024-10-29 11:44 UTC, daehwan2da commented on src/main/java/org/sopt/diary/api/DiaryController.java
> +		if (diaryUpdateRequest.body().length() > 30) {
create 의 NPE 의견과 같습니다.

2024-10-29 11:44 UTC, daehwan2da commented on src/main/java/org/sopt/diary/service/DiaryService.java
> +		if (!diaryEntity.getTitle().equals(diaryUpdateRequest.title())){
이 조건은 제거되어도 될것같은데 어떻게 생각하실까요?
```suggestion
		if (!diaryEntity.getTitle().equals(diaryUpdateRequest.title())){
```

2024-10-29 11:44 UTC, daehwan2da commented
`@Valid`를 사용하는 코드에 대해서 참조할수있는것 달라고했던것같아서 하나 남겨요~
- [예린이 PR](https://github.com/AND-SOPT-SERVER/yerin.lee/pull/5/files#diff-e7204c6146bc8bd7f24e7b40e321f54a56456e91b3aed7b97db087ddb23bc229R32)

---


Exception 과 ErrorCode 이 같은 역할을 중복으로 하고있지 않은지 고민해보면 좋겠어요
- BadRequestException (400), TooManyRequestException (429) 등 이미 Exception 에서 statusCode 를 담고있는데, errorCode 에서 또 담고있을 필요가있을지?
- 예외처리 관련한 부분은 합세 지나고 5~6주차쯤 다룰예정이에요
  - 예외도 Layer 마다 다르게 정의되는 방향이 좋은데요~ 이거 세미나에서 이야기해볼건데 미리 고민해보세요~
  - api (Controller) 레벨에서 정의되는 Exception 과 비즈니스 코어 로직에서 던지는 Exception 을 같이 써야할지?

게다가 ExceptionHandler 에서는 Exception 의 종류로만 응답에 status 를 넣어주고있네요~
---

2024-11-04 09:24 UTC, hyerinhwang-sailin commented on src/main/java/org/sopt/diary/service/DiaryService.java
> +		if (!diaryEntity.getTitle().equals(diaryUpdateRequest.title())){
해당 조건을 제거하면 제목을 변경하지 않고 다른 필드만 수정하려고 할 때도 제목이 이미 존재한다고 판단하여 에러가 발생하게 돼서 포함했습니다!

2024-11-05 08:14 UTC, merged